UCI-Chenli-teaching/spring19-cs221-project

- src/test/java/edu/uci/ics/cs221/analysis/punctuation/Team4PunctuationTokenizerTest.java
Team 4
test1 tests if the tokenizer can deal with empty string.
test2 tests if the tokenizer can tokenize normal string with white space.
test3 tests if the tokenizer can deal with any punctuations and regard other special characters as normal tokens.
test4 tests if the tokenizer could tokenize the string with multiple adjacent white spaces inside, before
and after it.
Yes
> [P1 tests] [Team 4] Add Punctuation Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/punctuation/Team2PunctuationTokenizerTest.java
Team 2
test1 tests if multiple newlines and tabs works.
test2 tests whether the tokenizer can deal with emojis.
test3 tests whether consecutive punctuation works.
Yes
> [P1 tests] [Team 2] Add Punctuation Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/punctuation/Team7PunctuationTokenizerTest.java
Team 7
test1 checks if the tokenizer can tokenize the input string with empty space and punctuations, and convert the tokens to lower case.
test2 tests if the tokenizer can deal with the empty string that only contains the space, table, and new line mark.
Yes
> [P1 tests] [Team 7] Add Punctuation Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/punctuation/Team1PunctuationTokenizerTest.java
Team 1
- `whiteSpacesShouldDelimit`: Test whether the punctuation tokenizer handles white spaces correctly.
- `punctuationsShouldDelimit`: Test whether the punctuation tokenizer handles punctuations correctly.
- `nonDelimiterShouldNotDelimit`: Test whether the punctuation tokenizer handles non-delimiter characters correctly.
- `tokensShouldBeLowerCase`: Test whether the punctuation tokenizer converts tokens into lower cases.
- `consecutiveWhiteSpacesShouldDelimit`: Test whether the punctuation tokenizer correctly handles consecutive whitespace characters.
- `consecutivePunctuationsShouldDelimit`: Test whether the punctuation tokenizer correctly handles consecutive punctuations.
- `surroundingWhiteSpacesShouldBeRemoved`: Test whether the punctuation tokenizer …
> [P1 tests] [Team 1] Add Punctuation Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/Team6PunctuationTokenizerTest.java
Team 6
Test Case 1 is to test if the tokenizer handles different white spaces correctly by having characters of \t,
\n and white spaces in the input text.
Test Case 2 is to test if the tokenizer can handle splits the text by given punctuations marks and removes them correctly.
The punctuations include ",", ".", ";", "?" and "!". Moreover, punctuation marks that are not on the list should not be
considered, such as i'am and four-year-old.
Test Case 3 is to test if the tokenizer can convert all tokens into lower case.
Test Case 4 is to test if the tokenizer can filter out the stop words.
Yes
> [P1 tests] [Team 6] Add Punctuation Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/stemmer/Team22PorterStemmerTest.java
Team 22
Porter Stemmer
test1 tests if the stemmer stems words end with "ible", "ize" and "ion" as well as words in the past tense.
test2 tests if the stemmer stems words end with "fully", "ator", "ment", "ness" and "ing".
test3 tests if the stemmer stems words end with "ance", "ate", "y", "val" and "ism".
Yes
> [P1 tests] [Team 22] Add Porter Stemmer Tests

- src/test/java/edu/uci/ics/cs221/analysis/wordbreak/Team12WordBreakTokenizer.java
Team 12
Word Break Tokenizer
test1 tests if tokenizer handles stop words
test2 tests capitalized letters and returning the best tokens based on probability
test3 tests when a text can't be broken to tokens
Yes
> [P1 tests] [Team 12] Add Word Break Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/stemmer/Team20PorterStemmerTest.java
1.Team Number- Team 20
2.Functionality under Test- Porter Stemmer
3.Description of tests - Test 1 checks that words that are already in their "root" forms are not modified.
Test 2 checks whether words in their plural forms are converted into their singular forms by the stemmer.
Test 3 checks if words with different forms of suffixes are converted to their root forms correctly.
Test 4 checks whether the stemmer is able to handle an empty string.
Test 5 checks if a sentence with different types of words is converted correctly.
4.Each test has comments.
> [P1 Tests][Team 20] Add Porter Stemmer Tests

- src/test/java/edu/uci/ics/cs221/analysis/wordbreak/Team9WordBreakTokenizerTest.java
What's your team number? Team 9
What is the functionality being tested? Wordbreak Tokenizer
Describe your tests briefly: 
test1 tests if the tokenizer handles empty input. 
test2 tests for upper case input.
test3 tests cases which have multiple answers.
test4 tests invalid input, expect an exception. Exception type depends on the implementation.
Does each test case have comments/documentation? 
Yes
> [P1 tests] [Team 9] Add Word Break Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/wordbreak/Team14WordBreakerTokenizerTest.java
Merge team 14 test cases to the base project
> [P1 tests] [Team 14] Add Word Breaker Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/analysis/punctuation/Team3PunctuationTokenizerTest.java
Team 3
team3TestCase1() tests if the tokenizer could split the text by the punctuation marks and change all the characters to lowercase.
team3TestCase2() tests if the tokenizer could automatically drop the stopwords such as "in" and "the", as well as single white spaces and multiple spaces.
team3TestCase3() tests if the tokenizer could deal with different kinds of spaces such as \n and \t.
Yes
> [P1 tests] [Team 3] Add Punctuation Tokenizer Tests 

- src/test/java/edu/uci/ics/cs221/analysis/stemmer/Team19PorterStemmerTest.java
Team 19
Porter Stemmer
test1 tests If the Stemmer can handle a text with multiple words with added suffix and complex pattern.
test2 tests If the Stemmer can handle a text with words with a complex pattern.
test3 tests If the Stemmer can handle a text with words with added suffix.
Yes
> [P1 tests] [Team 19] Add Porter Stemmer Tests

- src/test/java/edu/uci/ics/cs221/analysis/stemmer/Team21PorterStemmerTest.java
Team 21
Porter Stemmer
test1 tests stemming words with plurals and -ed or -ing suffixes.
test2 tests stemming words with -ization, -izer, -tional, -ibility, -ness suffixes.
test3 tests stemming words with -ment, -ness, -ence, -fulness, -ical, -ism suffixes.
Yes
> [P1 tests] [Team 21] Add Porter Stemmer Tests

- src/test/java/edu/uci/ics/cs221/analysis/wordbreak/Team17WordBreakTokenizerTest.java
- src/test/java/edu/uci/ics/cs221/analysis/wordbreak/WordBreakTokenizerTest.java
Team 17
Wordbreak Tokenizer
**test1** tests if the tokenizer handles combination tokens with mixed cases. 
**test2** tests if the tokenizer can handle really large strings and stop words efficiently.
**test3** has an empty string
**test4** has a punctuation in the string and the wordbreak tokenizer must throw an exception.
**test5** has two possible set of tokens. The wordbreak tokenizer must come up with the most optimal one.
Yes
> > 1. test5() should be tokenized to "hell", "orange" because "range" is not in the dictionary
> 
> "range" is in the dictionary : range 128314924
That'r right! range is present in the dictionary. @sadeemsaleh
> [P1 tests] [Team 17] Add Wordbreak Tokenizer Tests

- src/test/java/edu/uci/ics/cs221/index/Team17FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/Team17InvertedIndexManagerPart1Test.java
Team 17
Part 1, namely addDocument, flush, getNumSegments, getIndexSegment
**testInit** tests if getNumSegments() and getIndexSegment() work properly when creating a new folder.
**testAddDocumentFlush** tests if explicit call to flush() creates a disk segment correctly.
**testAutoFlush** tests if when flush threshold is reached, a segment is automatically created; also tests the correctness of such segment. 1000 documents of the same contents are added in the segment.
**testMixedDocumentAndFlush** tests if adding documents with different content works properly when explicit flush and automatic flush work properly together. 500 documents of 2 kinds are added in the second segment. …
> [P2 tests][Team 17]Add Task 1 Flush Tests

- src/test/java/edu/uci/ics/cs221/inverted/Team4OrSearchTest.java
Team 4
Test function `searchOrQuery( )` of InvertedIndexManager based on flush() and other basic functions.
**Test 1:**  Test for normal search or case.  This test case is going to search "cat" or "apple". The result should be doc1, doc2, doc3
**Test 2:**  Test for empty keyword.  Result should be an empty list of Documents
**Test 3:** Test for punctuation characters.  Results should be an empty list of Documents
Yes
> [P2 tests][Team 4]Add Task3: Boolean OR search Tests

- src/test/java/edu/uci/ics/cs221/index/Team14MergeSearchTest.java
Team 14
Testing to make sure that after merges the number of segments is always correct. We are also testing to make sure that the correct number of occurrences is present after merging multiple times, and that the number of documents is also correct.
Test 1: Merge each time a segment is created, this test makes sure that we only ever have a single segment.
Test 2: Merges every time we have 4 segments and then fully merges at the end. We check the number of documents in the final segment as well as the number of occurrences of some keywords in our documents.
Yes
> [P2 tests] [Team 14] Add Task 2 Merge Search Test

- src/test/java/edu/uci/ics/cs221/index/inverted/Team7AndSearchTest.java
Team 7
Boolean AND Search
"RightAndRight" tests if the InvertedIndexManger can return the correct result when the input query is valid.
"DuplicateRightAndRight" tests if the InvertedIndexManger can return the correct results when they are multiple possible documents.
"WrongAndWrong" tests if the InvertedIndexManger can return nothing when the input is not valid
Yes
> [P2 tests] [Team 7] Add Task3: Boolean AND Search

- src/test/java/edu/uci/ics/cs221/index/inverted/Team9KeywordSearchTest.java
Team 9
Test function searchQuery( ) of InvertedIndexManager based on flush() and other basic functions.
Test 1: Test for normal keyword search case. This test case is going to search "cat". The result should be doc1, doc3, doc4.
Test 3: Test same keyword after mergeAllSegments() is called. Results should be doc1, doc3, doc4
Test 3: Test for empty document store. Result should be an empty iterator of Documents.
Yes
> [P2 tests][Team9] Add Task3: Single Keyword Search Test

- src/test/java/edu/uci/ics/cs221/index/Team1StressTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team1StressTest.java
Team 1
Overall: Large Data Stress Test
- `test1`: Stress test with two large documents.
- `test2`: Stress test with ten smaller documents.
Yes
> [P2 tests] [Team 1] Add Overall: Large Data Stress Test

- src/test/java/edu/uci/ics/cs221/index/inverted/Team8KeywordSearchTest.java
Team 8
Single Keyword research
**Test 1**: test if the program works when doing single word searching.
**Test 2**: test if the program returns an empty list of Document when the query is empty.
**Test 3**: test if the program returns an empty list of Document when the query word is not in any document.
Yes
> [P2 tests][Team8] Add Task3: Single Keyword Search Test

- .gitignore
- src/test/java/edu/uci/ics/cs221/analysis/stemmer/Team22PorterStemmerTest.java
- src/test/java/edu/uci/ics/cs221/index/Team22FlushTest.java
Team 22
Task 1: Flush and Read Segments (no merge)
verifyContextTest  check whether flushed segments stored correctly
verifyContextTest check default flush threshold works correctly, especially for the context
checkEmptyTest tests corner case of flush() function when no documents is added v.s. add an empty document.
checkThresholdFlushTest tests if the system automatically calls flush() when reaching the default_flush_threshold.
checkPageIOTest tests if read/writer counter updated properly
Yes
> [P2 tests] [Team 22] Add Task 1 Flush Tests

- src/test/java/edu/uci/ics/cs221/index/Team2StressTest/Team2StressTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team2StressTest.java
Team 2
Overall Large Data Stress Test
The test add the novel "pride-and-prejudice" as one document(708KB) for 5000 times and added two additional test documents. The whole test data is about 3.46GB.
"test1" tests searchQuery with keyword "elizabeth" and see if it has appeared in the documents for 5001 times. If it is correct, it means the engine can handle very large datasets.
"test2" tests searchAndQuery with keyword "qwertyuiop" and "elizabeth" and see if it finds 1 record. If it passes the test, it means the searchAndQuery() works well in large datasets.
"test3" tests searchOrQuery with keyword "qwertyuiop" and "elizabeth" and see if it finds 5002 record. If it passes the test, it means the …
> [P2 tests] [Team 2] Add Overall: Large Data Stress Test

- src/test/java/edu/uci/ics/cs221/Team6AndSearchTest.java
Finished test cases for And search:
test1: test if normal input and output can work correctly
test2: test empty input and output
test3: test large word list
test4: test if exceptions could be correctly thrown when no element could be found
> [P2 tests] [Team 6] Add Overall: Boolean And Search Test

- src/test/java/edu/uci/ics/cs221/index/Team12MergeSearchTest.java
Team 12
Merge
test1 tests forceful merge before the threshold is reached.
test2 tests merge happening when threshold is reached.
Yes
> [P2 tests] [Team 12] Add Task 2 Merge Search Test

- src/test/java/edu/uci/ics/cs221/index/Team11MergeSearchTest.java
Team 11
Merge and search segments.
Test1: test an easy case of flush threshold=1 and merge threshold=2;
Test2: test when the number of segments is 3 and we forcefully call mergeAllSegments();
Test3: test when the flush and merge thresholds are 1 and 4 respectively;
Yes.
> [P2 tests] [Team 11] Add Task 2 Merge Segments Tests

- src/test/java/edu/uci/ics/cs221/storage/Team20FlushTest.java
Team 20
Task 1: Flush and Read Segments (no merge)
test1 changes the flush threshold to 2 and checks if flush() is automatically called after two documents are added. The no. of segments and the postings and document stores are checked.
test2 changes the flush threshold to 4and checks if flush() is automatically called after four documents are added. The no. of segments and the postings and document stores are checked.
test3  checks the result of flushing when the in-memory buffer is empty.
test4  checks if explicit calls to flush work when the no. of documents is below the threshold.
We use Junit @after to delete all written files after each test. …
> [P2 tests] [Team 20] Add Task 1 Flush Tests

- src/test/java/edu/uci/ics/cs221/index/inverted/InvertedIndexDeletionTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team10MergeTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team11MergeTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team12MergeTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team14MergeTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team17FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team18FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team19FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team20FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team21FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team22FlushTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team2StressTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team3StressTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team4OrSearchTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team5OrSearchTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team6AndSearchTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team7AndSearchTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team8KeywordSearchTest.java
- src/test/java/edu/uci/ics/cs221/index/inverted/Team9KeywordSearchTest.java
This is the change set to fix all student-written test cases for project 2. 
All test cases for project 2 are under folder `src/test/java/edu.ics.uci.cs221/index.inverted`.
For extra credit, add your own extra credit test cases in the file `InvertedIndexDeletionTest`, the TA will only look at this file.
> [P2 Tests] Fix all teams' test cases

- src/main/java/edu/uci/ics/cs221/index/inverted/Compressor.java
- src/main/java/edu/uci/ics/cs221/index/inverted/DeltaVarLenCompressor.java
- src/main/java/edu/uci/ics/cs221/index/inverted/InvertedIndexManager.java
- src/main/java/edu/uci/ics/cs221/index/inverted/NaiveCompressor.java
- src/main/java/edu/uci/ics/cs221/index/inverted/PositionalIndexSegmentForTest.java
This Pull Request adds new functions and classes for project 3.
> [P3] Add project 3 starter code

- src/test/java/edu/uci/ics/cs221/index/positional/Team2CompressorTest.java
Team 2
Compressor Correctness
How many test cases do you have?
4
`emptyTest` tests if the compressor works fine when the encoded and decoded subjects are empty.
`singleTest` tests single element inputs
`generalFullTest` tests on lists with different combinations of integers in both encode and decode functions, from the first element to the last element.
`decodeOffsetTest` tests if the offset feature in decode function works fine. We try different offsets and lengths on the testing byte array.
Yes
> [P3 tests][Team2] Add Task3: Compressor Correctness Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team3CompressorTest.java
Team 3
Task3: Compressor Correctness
How many test cases do you have?
8
testcase1 deals with the easiest encoding with input 123456. It aims to test the delta encoding which will turn it into 1 1 1 1 1 1.
testcase2 deals with input that will be compressed using multiple bytes.
testcase3 tests whether the encoder could handle the Integer.MAX_VALUE.
testcases 4-6 are just inverse tests of 1-3, which test the decoding of them.
testcases 7,8 test decoding from the chosen offset and length.
> [P3 tests][Team3] Add Task3: Compressor Correctness Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team5IndexCompressionTest.java
Team 5
Task3: Compare Index with Compression
- test1:  Test simple documents with same text, each key word show only one time each document mainly test inverted list since inverted list is long but positional list is short.
- test2:  Test docs with different text and each key word show multiple times in multiple document mainly test inverted list since inverted list is long but positional list is short.
- test3:  Test docs with different text and each key word show multiple times only in a document  mainly test positional  list since inverted  since  positional list is long.
- test4: Test add really long document, testing the positional list works or not mainly test positional  list since inverted  since  positional list is long.
Yes
> [P3 tests] [Team 5] Add Task3: Compare Index with Compression

- src/test/java/edu/uci/ics/cs221/index/positional/Team7IndexCompressionTest.java
Team 07
Compare Index with Compression
`addFewDocument` tests if the compression ratio right when adding a small number of documents.
`addLargeDocument` tests if the compression ratio right when adding a large number of documents.
Yes
> [P3 tests] [Team 7] Task3: Compare Index with Compression

- src/test/java/edu/uci/ics/cs221/index/inverted/Team9PositionalStressTest.java
- team9StressTest.txt
What's your team number? 
Team 9
 Overall: Large Data Stress Test
Describe your tests briefly: 
Test1 tests searchPhraseQuery, the keyword is “h” and it is a general stress positional test case. 
Test2 search a long list of phrase and test the correctness of its position.
Test3 search phrase “cat dog”, which is not in the resource text and should return empty.
 Yes
> [P3 tests] [Team 9] Add Overall: Large Data Stress Test

- src/test/java/edu/uci/ics/cs221/index/positional/Team10PositionalStressTest.java
Team 10
Overall Stress Test
test1 tests if searchQuery give right answers with large amount of data input.
test2 tests if Phrase Query work as expected.
test3 and test4 tests if position index work properly and if stopwords are ignored when calculate and store token positions.
Yes
> [P2 tests] [Team 10] Add Positional Stress Test

- src/test/java/edu/uci/ics/cs221/index/positional/Team12PhraseSearchTest.java
Team 12
Phrase Search
test1() tests if an empty phrase is searched
test2() tests if the words are present in the documents but not in consecutive order
test3() tests if more than a document is matching the query
test4() tests if the inverted index is not a positional index
test5() tests if search is done properly after merge
Yes
> [P3 tests] [Team 12] Phrase Search Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team14PhraseSearchTest.java
Team 14
Phrase Search
test1 tests phrase search when all the documents are on a single segment. This is checked against multiple different phrases.
test2 tests to see if the phrase isn't there that hasNext will return false right away
test3 tests phrase search when each of the documents is on a separate segment. For this test, we only check a single phrase.
Yes
> [P3 tests] [Team 14] Phrase Search Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team17PhraseSearchTest.java
Team 17
Phrase Search
testSearchEmptyPhrase tests if searching an empty phrase returns an empty iterator.
testSearchNonPositional tests if searching on an inverted index returns an UnsupportedOperationException.
testPopularPhrases tests if searching on a multi-word popular phrase from the dictionary works as intended.
testSearchSingleWordPhrase tests if searching on a single-word phrase returns the correct result. Also tests if searching after calling flush&merge works correctly; tests if hasNext() is not assumed to be called only once before next() is called.
testSearchMultiWordPhrase tests if searching on a multi-word phrase, containing stop words, returns the correct result. Also tests if …
> [P3 tests] [Team 17] Phrase Search Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team19PositionalFlushTest.java
Team 19
Positional Flush
test1: tests flush when flush() is called automatically, whether the total number of segments is correct and whether the first disk segment is set correctly.
test2: tests flush() has no operation when no document is added.
test3: tests flush() functionality as well as correct list of documents in a sample segment.
test4: after testing flush() functionality, this tests if the inverted list and the positional list are correct in a sample segment.
test5: tests flush() functionality, also tests two sample segments and their credibility
Yes
> [P3 tests] [Team 19] Positional Flush Tests

- src/test/java/edu/uci/ics/cs221/index/positional/Team22PositionalMergeTest.java
Team 22
Merge Positional Segments
simpleMergeTest test whether manually call mergeAllSegments() produces correct segment number and content
thresholdMergeTest test whether use default merge threshold produces correct segment number and content
Yes
> [P3 Test] [Team 22] Add Task1: Merge Positional Segments

- src/main/java/edu/uci/ics/cs221/index/inverted/InvertedIndexManager.java
This PR adds the new API needed by task 1.
> [P4] Add task 1 API

- src/test/java/edu/uci/ics/cs221/index/ranking/Team2GetNumDocumentsTest.java
- src/test/java/edu/uci/ics/cs221/index/ranking/Team2TfIdfTest.java
What's your team number? 
Team 2
getNumDocuments
Test1: Test number of document with a sample of documents (document number is below the merge threshold.)
Test2: Test number of documents after merge operation.
 Yes
> [P4 tests] [Team 2] Get Number of Documents

- src/test/java/edu/uci/ics/cs221/index/ranking/Team4TfIdfTest.java
What's your team number? 
Team 4
getDocumentFrequency
Test1: Test for DeltaVarLen compressor. See if the returned value is consistent with expected result.
Test2: Test for Naive compressor. Same operation as test1.
 Yes
> [P4 tests] [Team 4] Get Document Frequency

- src/test/java/edu/uci/ics/cs221/index/ranking/Team7TfIdfTest.java
Team 7
searchTfIdf()
Test1 tests if the Top K returned in the expected order.
Test2 tests if anything returns when search key is irrelevant.
Yes
> [P4 tests] [Team 7] Add searchTfIdf Tests

- src/test/java/edu/uci/ics/cs221/index/ranking/Team22TfIdfTest.java
What's your team number? 
Team 22
searchTfIdf
testOrderAndTopK: Test whether the searchTfidf function returns the correct order of topK documents.
testOrderAndNull: Test whether the searchTfidf function returns the correct result when topK is null.
 Yes
> [P4 tests] [Team 22] Add searchTfIdf tests 

- src/test/java/edu/uci/ics/cs221/index/ranking/Team12SearchTfIdf.java
Team 12
Search Tf-Idf
test1 tests if topk is null then should return all the documents.
test2 tests if the order of return documents is in descending order.
Yes
> [P4 tests] [Team 12] Add Tf-Idf Search tests

- src/test/java/edu/uci/ics/cs221/index/ranking/Team8TfIdfTest.java
Team 8
Search Tf-Idf
test1 tests if the function works well when topk is null.
test2 tests if the function works well with normal topk number.
Yes
> [P4 tests] [Team 8] Add Tf-Idf Search tests

- src/test/java/edu/uci/ics/cs221/index/ranking/Team19TfIdfTest.java
Team 19
Search TfIdf
test1: tests if the program returns the documents in two segments correctly
Yes
> [P4 tests] [Team 19] SearchTfIdf Test

- src/test/java/edu/uci/ics/cs221/Team6DocumentFrequencyTest.java
- src/test/java/edu/uci/ics/cs221/index/positional/Team6IndexCompressionTest.java
- What's your team number?
Team 6
- What is the functionality being tested?
Get Document Frequency
- Describe your tests briefly:
Test1 tests given different keywords, check if function can return correct frequency in different segments
Test2 tests given a specific keyword, check if the sum of frequency of different segments is accurate
- Does each test case have comments/documentation?
Yes
> [P4 tests] [Team 6] Get Document Frequency

- src/test/java/edu/uci/ics/cs221/index/ranking/Team17searchTfIdfTest.java
This PR contains more fixes to P4 tests.
Team 17 test 2 is removed because of duplicate scores.
> [P4 Tests] More fixes
